// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type AuthUser struct {
	ID                string
	Email             string
	PasswordSalt      string
	EncryptedPassword string
	PasswordCreatedAt time.Time
}

type Chatroom struct {
	ID        int64
	Name      string
	Creator   string
	CreatedAt time.Time
}

type ChatroomMember struct {
	ChatroomID    int64
	UserID        string
	ChatroomColor string
}

type Comment struct {
	ID        int64
	CreatedAt string
	Author    string
	Text      string
	Html      string
	PostID    int64
	ImageID   *int64
}

type CommentReply struct {
	CommentID      *int64
	ReplyCommentID *int64
}

type Image struct {
	ID    int64
	Image string
	Size  int64
	Ext   string
}

type Message struct {
	ID             int64
	AuthorID       *string
	AuthorUsername string
	Message        string
	RoomID         int64
	CreatedAt      time.Time
}

type Profile struct {
	ID              string
	Username        string
	GlobalChatColor string
}

type Token struct {
	ID        int64
	JwtType   string
	Jwt       string
	Valid     bool
	Family    string
	ExpiresAt int64
	Device    *string
	Ip        *string
	CreatedAt int64
}

type UsersToken struct {
	UserID  string
	TokenID int64
}
