// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Chatroom struct {
	ID        int64
	Name      string
	Creator   string
	CreatedAt time.Time
}

type ChatroomMember struct {
	ChatroomID int64
	UserID     string
}

type Comment struct {
	ID        int64
	CreatedAt string
	Author    string
	Text      string
	Html      string
	PostID    int64
	ImageID   *int64
}

type CommentReply struct {
	CommentID      *int64
	ReplyCommentID *int64
}

type Image struct {
	ID    int64
	Image string
	Size  int64
	Ext   string
}

type Message struct {
	ID        int64
	AuthorID  string
	Message   string
	RoomID    int64
	CreatedAt time.Time
}

type Profile struct {
	ID       string
	Username string
	Color    string
}
