// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Token struct {
	ID      int64
	JwtType string
	Jwt     string
	Valid   bool
	Family  string
}

type User struct {
	CreatedAt         string
	Username          string
	Email             sql.NullString
	EncryptedPassword string
	PasswordCreatedAt string
	ID                string
}

type UsersToken struct {
	ID      int64
	UserID  string
	TokenID int64
}
