// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Comment struct {
	ID        int64
	CreatedAt string
	Author    string
	Text      string
	Html      string
	PostID    int64
}
